name = "paywall-worker"
main = "paywall-worker.js"
compatibility_date = "2025-12-06"

[[kv_namespaces]]
binding = "PAYWALL_DB"
id = "f573def1f793421a800f1551bdc53378"

[vars]
API_BASE_URL = "https://d2b57a8a3394.ngrok-free.app"
