name = "paywall-worker"
main = "paywall-worker.js"
compatibility_date = "2025-12-06"
account_id = "1ceff0306c65aeb052307de380ea962e"

# Routes configuration
routes = [
  { pattern = "test-cloudflare-website.adarsh.software/*", zone_id = "11685346bf13dc3ffebc9cc2866a8105" }
]

# Environment variables for password authentication
[vars]
ACCESS_PASSWORD = "secret123"
LOGGING = "true"
ORIGIN_URL = "https://test-paywall-website.adarsh.software"
ZONE_ID = "11685346bf13dc3ffebc9cc2866a8105"
API_TOKEN = "oWN3t2VfMulCIBh7BzrScK87xlKmPRp6a1ttKVsB"
PAYMENT_ADDRESS = "0xea859ca79b267afdb7bd7702cd93c4e7c0db16ecaca862fb38c63d928f821a1b"
MOVEMENT_RPC_URL = "https://testnet.movementnetwork.xyz/v1"

[[kv_namespaces]]
binding = "PAYWALL_DB"
id = "f573def1f793421a800f1551bdc53378"