name = "paywall-worker"
main = "paywall-worker.js"
compatibility_date = "2024-01-01"

route = "test-cloudflare-website.adarsh.software/*"
zone_id = "11685346bf13dc3ffebc9cc2866a8105"

[vars]
ORIGIN_URL = "https://test-cloudflare-website.adarsh.software"