name = "paywall-worker"
main = "paywall-worker.js"
compatibility_date = "2025-12-06"
account_id = "1ceff0306c65aeb052307de380ea962e"

# Environment variables for password authentication
[vars]
ACCESS_PASSWORD = "secret123"
LOGGING = "true"

[[kv_namespaces]]
binding = "PAYWALL_DB"
id = "f573def1f793421a800f1551bdc53378"